stages:
  - build
  - test
  - sonar
  - deploy

build:
  stage: build
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test

sonar:
  stage: sonar
  script:
    - cd Software/Backend
    - gradle sonarqube -D "sonar.projectKey=Individual-Track" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=sqp_2d60a928e16ba54f1661b9690b21320aadd40d65"

deploy:
  stage: deploy
  script:
    - cd Software
    - docker-compose up -d
    - docker ps

after_script:
  - echo "End CI"
  - exit
