stages:
  - build
  - test
  - sonar
  - deploy

build:
  stage: build
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test

sonar:
  stage: sonar
  script:
    - cd Software/Backend
    - gradle sonarqube -D "sonar.projectKey=Individual-Track-Springboot" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=sqp_227106a49801bb7a81851020ec16ca3b48a00621"

deploy:
  stage: deploy
  script:
    - cd Software
    - docker-compose up -d
    - docker ps

after_script:
  - echo "End CI"
  - exit
