stages:
  - build
  - test
  - sonar
  - deploy

build:
  stage: build
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test

sonar:
  stage: sonar
  script:
    - cd Software/Backend
    - gradle sonarqube -D "sonar.projectKey=Individual-Track-Project" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=f62fc0ab5c799818d2f1e3d5a52778e1591f0cbd"

deploy:
  stage: deploy
  script:
    - cd Software
    - docker-compose up -d
    - docker ps

after_script:
  - echo "End CI"
  - exit
