stages:
  -build
  -test
  -analyze

build:
  stage: build
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test

analyze:
  stage: analyze
  script:
    - cd Software/Backend
    - gradle sonarqube \
      -Dsonar.projectKey=Individual-Track \
      -Dsonar.host.url=http://localhost:9000 \
      -Dsonar.login=f62fc0ab5c799818d2f1e3d5a52778e1591f0cbd
    allow_failure: true
    
after_script:
  - echo "End CI"
  - exit
