build:
  stage: build
  script:
    - ./gradle build -x test
   # - ./gradlew.bat --stop
test:
  stage: test
  script:
    - ./gradle test
   # - ./gradlew.bat -stop
after_script:
  - echo "End CI"
  - exit