build:
  stage: build
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test

    - echo "Test Using SonarQube"
    - gradle sonarqube \
      -Dsonar.projectKey=Individual-Track-Project \
      -Dsonar.host.url=http://localhost:9000 \
      -Dsonar.login=f62fc0ab5c799818d2f1e3d5a52778e1591f0cbd
    
after_script:
  - echo "End CI"
  - exit
