stages:
  - build
  - test
  - sonar
  - deploy
  - cypress

build:
  stage: build
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test

sonar:
  stage: sonar
  script:
    - cd Software/Backend
    - gradle sonarqube -D "sonar.projectKey=Individual-Track-Spring" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=sqp_899cd355780972c2cdc5ebbc676f85933507c446"

deploy:
  stage: deploy
  script:
    - cd Software
    - docker-compose up -d
    - docker ps

cypress:
  image: cypress/base:10
  stage: cypress
  script:
    - docker run --publish 3000:3000 --name react-standalone react-standalone-image
    - cd Software/frontend.v5
    - npm run runHeadless

after_script:
  - echo "End CI"
  - exit
