build:
  stage: build
    
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test
    
after_script:
  - echo "End CI"
  - exit