stages:
  - build
  - test
  - sonar
  - deploy
  - cypress

build:
  stage: build
  script:
    - cd Software/Backend
    - gradle build -x test

test:
  stage: test
  script:
    - cd Software/Backend
    - gradle test

sonar:
  stage: sonar
  script:
    - cd Software/Backend
    - gradle sonarqube -D "sonar.projectKey=Individual-Track-Springboot" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=sqp_f1b44088638d101b9a4e63a8166fd2dc43aebb64"

deploy:
  stage: deploy
  script:
    - cd Software
    - docker-compose up -d
    - docker ps
    - docker-compose stop

cypress:
  image: cypress/base:10
  stage: cypress
  script:
    - cd Software/frontend.v5
    - npm install --legacy-peer-deps
    - npm install pm2 -g
    - pm2 --name MyReactApp start npm -- start
    - npm run runHeadless
    - pm2 delete 0

after_script:
  - echo "End CI"
  - exit
