gitlab_runner_pipeline_config:
tags:
   - ci
build:
 stage: build
 script:
   - ./gradlew build -x test
   - ./gradlew.bat --stop 
test:
  stage: test
  script:
   - ./gradlew test
   - ./gradlew.bat –stop

after_script:
   - echo "End CI“
   - exit
