version: "3.8"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/Backend/backend
    ports:
      - 8080:8080
    image: backend:springboot
    container_name: spring_container
    command: java -jar ./Backend/build/libs/individual-track-spring-backend-0.0.1-SNAPSHOT.jar
  frontend:
    build:
      context: ./frontend.v5
      dockerfile: Dockerfile
    volumes:
      - ./frontend.v5:/frontend.v5/frontend
    ports:
      - 3000:3000
    image: frontend:react
    container_name: react_container
    command: npm start
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network
